# This file has 3 INTENTIONAL ERRORS - Find them!
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: microshop
#  namespace: argocd 
#spec:
#  project: default
#  source:
#    repoURL: https://github.com/navaneethanparam/final-devops-project.git
#    targetRevision: main
#    path: k8s/base
 # destination:
#    server: https://kubernetes.default.svc
#    namespace: default
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - CreateNamespace = true  # ERROR 2: Should be true